import type { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AUTH_COOKIE } from './auth/auth.constants.js';
import metadata from './metadata.js';

export const DOCS_PATH = 'api/docs';

// On Vercel the function bundle holds only files the code imports, so the
// Swagger UI assets that @nestjs/swagger serves from disk are missing and the
// page stays blank. There the same assets load from a CDN instead; Docker
// and local runs keep serving the bundled copies.
const SWAGGER_UI_CDN = 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5';
const cdnAssets = process.env.VERCEL
  ? {
      customCssUrl: `${SWAGGER_UI_CDN}/swagger-ui.css`,
      customJs: [
        `${SWAGGER_UI_CDN}/swagger-ui-bundle.js`,
        `${SWAGGER_UI_CDN}/swagger-ui-standalone-preset.js`,
      ],
    }
  : {};

/**
 * Interactive API docs at /api/docs (JSON at /api/docs/json), generated from
 * the controllers and DTOs. Sign in through POST /api/auth/signin in the UI
 * and the session cookie is used for the other calls.
 */
export async function setupDocs(app: INestApplication): Promise<void> {
  // DTO and response schemas, generated by `npm run docs:metadata`.
  await SwaggerModule.loadPluginMetadata(metadata);

  const config = new DocumentBuilder()
    .setTitle('Dhaka Tesla Pool API')
    .setDescription(
      'Share a seat. Split the fare. Survive Dhaka traffic.\n\n' +
        'Money is in integer paisa (৳1 = 100). Demo accounts: ' +
        '`jashim@dhakatesla.test` (driver), `nusrat@`, `rafiq@`, ' +
        '`shirin@dhakatesla.test` (passengers), password `tesla1234`.',
    )
    .setVersion('1.0')
    .addCookieAuth(AUTH_COOKIE)
    .build();

  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup(DOCS_PATH, app, document, {
    jsonDocumentUrl: `${DOCS_PATH}/json`,
    customSiteTitle: 'Dhaka Tesla Pool API',
    ...cdnAssets,
    swaggerOptions: { withCredentials: true, persistAuthorization: true },
  });
}
